name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install local packages.
      run: python -m pip install packages/*

    - name: Install remote packages.
      run: python -m pip install -r requirements.txt

    - name: Run unit-tests.
      run: python -m unittest discover -v
      working-directory: tests
